# Informasi Dasar Situs
title: Underground Coder
email: arcacoder@gmail.com
description: >- # Deskripsi singkat situs Anda
  Portal pembelajaran Exploit Development dan Cybersecurity.
baseurl: "" # Kosongkan jika menggunakan domain username.github.io
url: "" # Link web Anda nantinya

# Konfigurasi Collections (PENTING!)
# Ini yang membuat folder _materi terbaca sebagai daftar materi otomatis
collections:
  materi:
    output: true
    permalink: /:collections/:path/
    
collections:
  kategori:
    output: true  # WAJIB agar file di dalam _kategori jadi halaman .html
    permalink: /:name/ # Opsional, jika ingin otomatis mengikuti nama file

# Pengaturan Build
markdown: kramdown
highlighter: rouge
lsi: false

# Pengaturan Exclude
# File atau folder yang tidak perlu diproses oleh Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  
kategori:
  - Basic
  - Web Application
  - Network and Protocol
  - Binary Exploitation
  - Shellcoding
  - Client Side
  - Python Basic
  - Miscellaneous
  - Excercises